### ISSUE TITLE
应用在ESP32上时会报错

### ISSUE THREAD

**Issue by conghuang** [ALICHOUCHENE/Qmi8658c#1]
您的驱动写的很干净，可是在我应用在ESP32上时会报错，请协助

WARNING: library Qmi8658c claims to run on avr architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).
In file included from d:\Documents\Arduino\libraries\Qmi8658c\src\Qmi8658c.cpp:25:
C:\Users\hc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\Wire\src/Wire.h: In member function 'uint8_t Qmi8658c::qmi8658_read(uint8_t)':
C:\Users\hc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\Wire\src/Wire.h:127:13: note: candidate 1: 'uint8_t TwoWire::requestFrom(int, int)'
     uint8_t requestFrom(int address, int size);
             ^~~~~~~~~~~
C:\Users\hc\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.14\libraries\Wire\src/Wire.h:125:13: note: candidate 2: 'uint8_t TwoWire::requestFrom(uint8_t, uint8_t)'
     uint8_t requestFrom(uint8_t address, uint8_t size);
             ^~~~~~~~~~~
d:\Documents\Arduino\libraries\Qmi8658c\src\Qmi8658c.cpp:93:10: error: return-statement with no value, in function returning 'uint8_t' {aka 'unsigned char'} [-fpermissive]
          return;
          ^~~~~~

exit status 1

Compilation error: exit status 1

**Comment by ALICHOUCHENE** [comment]
@conghuang 
The library was essentially developed  and tested to run only on Arduino boards and hasn't been adapted for ESP32 boards.
